version: '2'

services:
  web:
    build: .
    links:
      - "db:database"
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - "YESOD_MYSQL_USER=dbuser"
      - "YESOD_MYSQL_PASSWORD=${PASSWORD}"
      - "YESOD_MYSQL_DATABASE=mpd"
      - YESOD_MYSQL_HOST=database
      - YESOD_MYSQL_PORT=3306
      - YESOD_HOST=web
      - YESOD_PORT=3000
    volumes:
      - .:/app:ro
      - .data/static:/app/static
      - .data/config:/app/config
  db:
    image: mariadb:10.4
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${PASSWORD}"
      - "MYSQL_USER=dbuser"
      - "MYSQL_PASSWORD=${PASSWORD}"
      - "MYSQL_DATABASE=mpd"
    volumes:
      - .data/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
